---
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: install packages
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - tree
        - wget
        - zip
        - unzip
